version: "3"

services:
  database:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: dbuser
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - bjw_net

  backend:
    image: node:current-alpine3.12
    restart: always
    container_name: backend
    environment:
      - NODE_ENV=dev
      - DATABASE_URI=mongodb://dbuser:dbuser@database:27017
    volumes:
      - ./bjwbackend:/app
    entrypoint: "/app/entrypoint.sh"
    depends_on:
      - database
    networks:
      - bjw_net

  frontend:
    image: node:current-alpine3.12
    restart: always
    container_name: frontend
    environment:
      - NODE_ENV=dev
      - CI=true
    volumes:
      - ./bjwfrontend:/app
    entrypoint: "/app/entrypoint.sh"
    depends_on:
      - backend
    networks:
      - bjw_net

  webserver:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker-local/nginx/fb.conf:/etc/nginx/conf.d/default.conf
      - ./docker-local/nginx/nginx_logs:/var/log/nginx/
      - ./bjwbackend:/backend
    networks:
      - bjw_net
    depends_on:
      - frontend
      - backend

networks:
  bjw_net:
    driver: bridge

volumes:
  mongodb_data_container: