export {default as Home} from './home/HomePage'
export {default as Admin} from './admin/AdminPage'
export {default as Submissions} from './submissions/SubmissionsPage'
export {default as Invoice} from './invoice/InvoicePage'
export {default as Login} from './login/LoginPage'
export {default as Register} from './register/RegisterPage'
export {default as PasswordReset} from './resetpassword/PasswordResetPage'
export {default as Orders} from './orders/OrdersPage'